### ISSUE TITLE
报错页面

### ISSUE THREAD

**Issue by xxsmile123** [kelvinBen/AppInfoScanner#12]
当前环境：
python 3.8.7
win 10企业版 1909
AppInfoScanner版本：1.0.8

报错现象：
        *多余目录         -1    D:\security_tools\APP\AppInfoScanner\out\baihe_android_tuiguang1296_y_10_22_0\unknown\javax\annotation\concurrent\
          *多余文件                 1611        GuardedBy.java
          *多余文件                 1333        Immutable.java
          *多余文件                  892        NotThreadSafe.java
          *多余文件                  752        ThreadSafe.java
        *多余目录         -1    D:\security_tools\APP\AppInfoScanner\out\baihe_android_tuiguang1296_y_10_22_0\unknown\javax\annotation\meta\
          *多余文件                  650        Exclusive.java
          *多余文件                 1097        Exhaustive.java
          *多余文件                  796        TypeQualifier.java
          *多余文件                  590        TypeQualifierDefault.java
          *多余文件                  822        TypeQualifierNickname.java
          *多余文件                  687        TypeQualifierValidator.java
          *多余文件                  639        When.java
        *多余目录         -1    D:\security_tools\APP\AppInfoScanner\out\baihe_android_tuiguang1296_y_10_22_0\unknown\okhttp3\
        *多余目录         -1    D:\security_tools\APP\AppInfoScanner\out\baihe_android_tuiguang1296_y_10_22_0\unknown\okhttp3\internal\
        *多余目录         -1    D:\security_tools\APP\AppInfoScanner\out\baihe_android_tuiguang1296_y_10_22_0\unknown\okhttp3\internal\publicsuffix\
          *多余文件                34000        publicsuffixes.gz
        *多余目录         -1    D:\security_tools\APP\AppInfoScanner\out\baihe_android_tuiguang1296_y_10_22_0\unknown\org\
        *多余目录         -1    D:\security_tools\APP\AppInfoScanner\out\baihe_android_tuiguang1296_y_10_22_0\unknown\org\apache\
        *多余目录         -1    D:\security_tools\APP\AppInfoScanner\out\baihe_android_tuiguang1296_y_10_22_0\unknown\org\apache\http\
        *多余目录         -1    D:\security_tools\APP\AppInfoScanner\out\baihe_android_tuiguang1296_y_10_22_0\unknown\org\apache\http\entity\
        *多余目录         -1    D:\security_tools\APP\AppInfoScanner\out\baihe_android_tuiguang1296_y_10_22_0\unknown\org\apache\http\entity\mime\
          *多余文件                  907        version.properties

------------------------------------------------------------------------------

                  总数        复制        跳过       不匹配        失败        其他
       目录:         1         0         1         0         0      3068
       文件:         0         0         0         0         0     27344
       字节:         0         0         0         0         0  234.44 m
       时间:   0:00:31   0:00:00                       0:00:00   0:00:31
   结束时间: 2021年11月8日 11:24:01

Traceback (most recent call last):
  File "app.py", line 72, in <module>
    main()
  File "app.py", line 69, in main
    cli()
  File "E:\python3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "E:\python3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "E:\python3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\python3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\python3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "app.py", line 32, in android
    raise e
  File "app.py", line 28, in android
    bootstrapper.init()
  File "D:\security_tools\APP\AppInfoScanner\libs\core\__init__.py", line 99, in init
    os.makedirs(output_path)
  File "E:\python3\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'D:\\security_tools\\APP\\AppInfoScanner\\out'

**Comment by kelvinBen** [comment]
版本: 1.0.10版本已修复，使用过程中如还存在问题请再反馈
