### ISSUE TITLE
AttributeError: 'WrappedSocket' object has no attribute 'getpeername'

### ISSUE THREAD

**Issue by N0o01** [kelvinBen/AppInfoScanner#15]
AttributeError: 'WrappedSocket' object has no attribute 'getpeername'
Exception in thread Thread - 2:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Applications/Xc7ACD/APP/AppInfoScanner/libs/core/net.py", line 88, in run
    self.__get_Http_info__(threadLock)
  File "/Applications/Xc7ACD/APP/AppInfoScanner/libs/core/net.py", line 29, in __get_Http_info__
    result = self.__get_request_result__(url_ip)
  File "/Applications/Xc7ACD/APP/AppInfoScanner/libs/core/net.py", line 66, in __get_request_result__
    des_ip = sock.getpeername()[0]
AttributeError: 'WrappedSocket' object has no attribute 'getpeername'

**Comment by kelvinBen** [comment]
这个问题与本地环境有关系，可以尝试更新一下本地python环境

**Comment by kelvinBen** [comment]
版本: 1.0.10版本已修复，使用过程中如还存在问题请再反馈
