### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: Invalid chunk type

### ISSUE THREAD

**Issue by websecer** [kelvinBen/AppInfoScanner#17]
Exception in thread "main" brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000203
	at brut.androlib.res.decoder.ARSCDecoder.checkChunkType(ARSCDecoder.java:544)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:88)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:790)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
	at brut.androlib.Androlib.getResTable(Androlib.java:66)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:179)
	at brut.apktool.Main.main(Main.java:82)
[-] Decompilation failed, please submit error information at https://github.com/kelvinBen/AppInfoScanner/issues
Traceback (most recent call last):
  File "/opt/AppInfoScanner/app.py", line 72, in <module>
    main()
  File "/opt/AppInfoScanner/app.py", line 69, in main
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/AppInfoScanner/app.py", line 32, in android
    raise e
  File "/opt/AppInfoScanner/app.py", line 30, in android
    BaseTask("Android", inputs, rules, sniffer, threads, package).start()
  File "/opt/AppInfoScanner/libs/task/base_task.py", line 46, in start
    task_info = self.__tast_control__()
  File "/opt/AppInfoScanner/libs/task/base_task.py", line 85, in __tast_control__
    task_info = AndroidTask(cacar_path,self.package).start()
  File "/opt/AppInfoScanner/libs/task/android_task.py", line 32, in start
    self.__decode_dir__(input_file_path)
  File "/opt/AppInfoScanner/libs/task/android_task.py", line 74, in __decode_dir__
    if self.__decode_file__(dir_or_file_path) == "error":
  File "/opt/AppInfoScanner/libs/task/android_task.py", line 49, in __decode_file__
    self.__decode_apk__(file_path,apktool_path,output_path)
  File "/opt/AppInfoScanner/libs/task/android_task.py", line 85, in __decode_apk__
    raise Exception(file_path + ", Decompilation failed.")
Exception: /media/sf_share-disk/wandou/test.apk, Decompilation failed.

**Comment by kelvinBen** [comment]
这个APK的一些文件被修改了，导致不能进行反编译处理，方便的话发一下APK文件

**Comment by websecer** [comment]
apk不太方便，这个可以忽略吗，比如这个apk不管是加壳了还是其他的原因导致无法扫描了，就忽略这个错误，继续扫描下一个

**Comment by kelvinBen** [comment]
可以的
