### ISSUE TITLE
解析ipa报错

### ISSUE THREAD

**Issue by tomchen008** [kelvinBen/AppInfoScanner#2]
[*] Create directory D:\AppInfoScanner\out
[*] AI is analyzing filtering rules......
[*] The filtering rules obtained by AI are as follows: {'.*w3.org', '.*0.0.0.0', '.*apache.org', '.*localhost', '.*umeng.com', '.*umengcloud.com', '.*.amap.com', '.*jpush.cn', '.*github.com', '.*127.0.0.1', '.*apple.com', '.*w3school.com.cn', '.*android.com'}
Traceback (most recent call last):
  File "D:\AppInfoScanner\app.py", line 72, in <module>
    main()
  File "D:\AppInfoScanner\app.py", line 69, in main
    cli()
  File "C:\Users\58891\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\58891\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\58891\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\58891\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\58891\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\AppInfoScanner\app.py", line 49, in ios
    raise e
  File "D:\AppInfoScanner\app.py", line 47, in ios
    BaseTask("iOS", inputs, rules, sniffer, threads).start()
  File "D:\AppInfoScanner\libs\task\base_task.py", line 45, in start
    task_info = self.__tast_control__()
  File "D:\AppInfoScanner\libs\task\base_task.py", line 87, in __tast_control__
    task_info = iOSTask(cacar_path).start()
  File "D:\AppInfoScanner\libs\task\ios_task.py", line 25, in start
    self.__decode_ipa__(cores.output_path)
  File "D:\AppInfoScanner\libs\task\ios_task.py", line 96, in __decode_ipa__
    old_zip_dir = self.__get_parse_dir__(output_path,zip_file_names[0])
  File "D:\AppInfoScanner\libs\task\ios_task.py", line 124, in __get_parse_dir__
    end = file_path.index(".app")
ValueError: substring not found

**Comment by kelvinBen** [comment]
@tomchen008 您好！BUG已确认，临时解决方案如下：

请使用IDE工具打开 D:\AppInfoScanner\libs\task\ios_task.py 将第96行～98行代码删除(即下述代码)，然后保存代码，重复以上操作即可。

```
old_zip_dir = self.__get_parse_dir__(output_path,zip_file_names[0])
new_zip_dir = self.__get_parse_dir__(output_path,new_zip_file)
os.rename(old_zip_dir,new_zip_dir)
```

这个问题会在下一版本解决，请关注最新版本更新。

感谢提交BUG反馈
