### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by yannhank** [kelvinBen/AppInfoScanner#26]
└─# python app.py android -i app/1667305394914.apk 
[*] Create directory /root/tools/6-appinfo/appInfoScanner/out
[*] AI is analyzing filtering rules......
[*] The filtering rules obtained by AI are as follows: {'.*apache.org', '.*w3school.com.cn', '.*127.0.0.1', '.*w3.org', '.*umengcloud.com', '.*jpush.cn', '.*localhost', '.*android.com', '.*umeng.com', '.*apple.com', '.*0.0.0.0', '.*.amap.com', '.*github.com', '.*slf4j.org'}
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Debian-1, mixed mode, sharing)
I: Using Apktool 2.6.1 on 1667305394914.apk
I: Loading resource table...
W: Skipping package group: cai.dongfandsfadsgcaifuailiaot.caifudg
I: Decoding AndroidManifest.xml with resources...
Exception in thread "main" brut.androlib.err.RawXmlEncounteredException: Could not decode XML
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:145)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:151)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:159)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:193)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:141)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:79)
Caused by: java.io.IOException: Expected: 0x00080003 or 0x00080001, got: 0x00080000
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:45)
	at brut.androlib.res.decoder.AXmlResourceParser.doNext(AXmlResourceParser.java:808)
	at brut.androlib.res.decoder.AXmlResourceParser.next(AXmlResourceParser.java:98)
	at brut.androlib.res.decoder.AXmlResourceParser.nextToken(AXmlResourceParser.java:108)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.nextToken(XmlPullParserDelegate.java:105)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:138)
	... 7 more
[-] Decompilation failed, please submit error information at https://github.com/kelvinBen/AppInfoScanner/issues
Traceback (most recent call last):
  File "/root/tools/6-appinfo/appInfoScanner/app.py", line 79, in <module>
    main()
  File "/root/tools/6-appinfo/appInfoScanner/app.py", line 75, in main
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/tools/6-appinfo/appInfoScanner/app.py", line 35, in android
    raise e
  File "/root/tools/6-appinfo/appInfoScanner/app.py", line 33, in android
    BaseTask("Android", inputs, rules, sniffer, threads, package).start()
  File "/root/tools/6-appinfo/appInfoScanner/libs/task/base_task.py", line 47, in start
    task_info = self.__tast_control__()
  File "/root/tools/6-appinfo/appInfoScanner/libs/task/base_task.py", line 89, in __tast_control__
    task_info = AndroidTask(cacar_path, self.package).start()
  File "/root/tools/6-appinfo/appInfoScanner/libs/task/android_task.py", line 35, in start
    if self.__decode_file__(input_file_path) == "error":
  File "/root/tools/6-appinfo/appInfoScanner/libs/task/android_task.py", line 51, in __decode_file__
    self.__decode_apk__(file_path, apktool_path, output_path)
  File "/root/tools/6-appinfo/appInfoScanner/libs/task/android_task.py", line 88, in __decode_apk__
    raise Exception(file_path + ", Decompilation failed.")
Exception: app/1667305394914.apk, Decompilation failed.

**Comment by zhangyuhaimian** [comment]
找到原因了么

**Comment by kelvinBen** [comment]
版本: 1.0.10版本已修复，使用过程中如还存在问题请再反馈
