### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hkcitizens9527** [kelvinBen/AppInfoScanner#31]
how to do this????????

Traceback (most recent call last):
  File "/home/chris/V1.0.8_Releases/app.py", line 79, in <module>
    main()
  File "/home/chris/V1.0.8_Releases/app.py", line 75, in main
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/chris/V1.0.8_Releases/app.py", line 35, in android
    raise e
  File "/home/chris/V1.0.8_Releases/app.py", line 33, in android
    BaseTask("Android", inputs, rules, sniffer, threads, package).start()
  File "/home/chris/V1.0.8_Releases/libs/task/base_task.py", line 47, in start
    task_info = self.__tast_control__()
  File "/home/chris/V1.0.8_Releases/libs/task/base_task.py", line 89, in __tast_control__
    task_info = AndroidTask(cacar_path, self.package).start()
  File "/home/chris/V1.0.8_Releases/libs/task/android_task.py", line 35, in start
    if self.__decode_file__(input_file_path) == "error":
  File "/home/chris/V1.0.8_Releases/libs/task/android_task.py", line 51, in __decode_file__
    self.__decode_apk__(file_path, apktool_path, output_path)
  File "/home/chris/V1.0.8_Releases/libs/task/android_task.py", line 88, in __decode_apk__
    raise Exception(file_path + ", Decompilation failed.")
Exception: LeaveHomeSafe_3.5.2.apk, Decompilation failed.

**Comment by hkcitizens9527** [comment]
can not  Decompilation
