### ISSUE TITLE
Exception: Please install the Java environment!

### ISSUE THREAD

**Issue by R00T-1024** [kelvinBen/AppInfoScanner#33]
PS D:\Tools\渗透测试\APP\AppinfoScanner_V1.0.8_Releases> python.exe .\app.py android -i C:\Users\Administrator\Downloads\6399.apk
[*] Create directory D:\Tools\渗透测试\APP\AppinfoScanner_V1.0.8_Releases\out
[*] AI is analyzing filtering rules......
[*] The filtering rules obtained by AI are as follows: {'.*apache.org', '.*apple.com', '.*jpush.cn', '.*github.com', '.*0.0.0.0', '.*w3school.com.cn', '.*localhost', '.*w3.org', '.*umeng.com', '.*android.com', '.*.amap.com', '.*127.0.0.1', '.*umengcloud.com', '.*slf4j.org'}
系统找不到指定的路径。
java version "1.8.0_351"
Java(TM) SE Runtime Environment (build 1.8.0_351-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.351-b10, mixed mode)
Traceback (most recent call last):
  File "D:\Tools\渗透测试\APP\AppinfoScanner_V1.0.8_Releases\app.py", line 79, in <module>
    main()
  File "D:\Tools\渗透测试\APP\AppinfoScanner_V1.0.8_Releases\app.py", line 75, in main
    cli()
  File "D:\install\python39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\install\python39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\install\python39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\install\python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\install\python39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Tools\渗透测试\APP\AppinfoScanner_V1.0.8_Releases\app.py", line 35, in android
    raise e
  File "D:\Tools\渗透测试\APP\AppinfoScanner_V1.0.8_Releases\app.py", line 33, in android
    BaseTask("Android", inputs, rules, sniffer, threads, package).start()
  File "D:\Tools\渗透测试\APP\AppinfoScanner_V1.0.8_Releases\libs\task\base_task.py", line 47, in start
    task_info = self.__tast_control__()
  File "D:\Tools\渗透测试\APP\AppinfoScanner_V1.0.8_Releases\libs\task\base_task.py", line 89, in __tast_control__
    task_info = AndroidTask(cacar_path, self.package).start()
  File "D:\Tools\渗透测试\APP\AppinfoScanner_V1.0.8_Releases\libs\task\android_task.py", line 28, in start
    raise Exception("Please install the Java environment!")
Exception: Please install the Java environment!

**Comment by XXXE88** [comment]
java  环境变量

**Comment by R00T-1024** [comment]
设置好了环境变量还是不行

**Comment by R00T-1024** [comment]
![图片](https://user-images.githubusercontent.com/84626690/224529303-20d252bb-2aff-4a13-8ba9-2897b9b9848e.png)

**Comment by R00T-1024** [comment]
![图片](https://user-images.githubusercontent.com/84626690/224529330-4e945b6e-3aa2-4742-9800-66c15e143903.png)

**Comment by R00T-1024** [comment]
![图片](https://user-images.githubusercontent.com/84626690/224529375-558e4f36-acc0-4c61-b381-b40326bf0501.png)

**Comment by R00T-1024** [comment]
![图片](https://user-images.githubusercontent.com/84626690/224529429-f5f8cb9d-0988-43df-a3e6-fc4ff20a6d7f.png)

**Comment by lanyinglinglong** [comment]
同样遇到了这个问题

**Comment by kelvinBen** [comment]
这个应该是多环境变量导致的冲突，版本: 1.0.10版本已调整了命令行的调用方式，可以下载试试看
