### ISSUE TITLE
Decompilation failed, please submit error information at

### ISSUE THREAD

**Issue by qySec** [kelvinBen/AppInfoScanner#38]
反编译失败：
Exception in thread "main" java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Unknown Source)
        at java.util.regex.Matcher.reset(Unknown Source)
        at java.util.regex.Matcher.<init>(Unknown Source)
        at java.util.regex.Pattern.matcher(Unknown Source)
        at brut.androlib.res.decoder.AndroidManifestResourceParser.isNumericStringMetadataAttributeValue(AndroidManifestResourceParser.java:56)
        at brut.androlib.res.decoder.AndroidManifestResourceParser.getAttributeValue(AndroidManifestResourceParser.java:41)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:80)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:139)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:151)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:159)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:193)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:141)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:79)
[-] Decompilation failed, please submit error information at https://github.com/kelvinBen/AppInfoScanner/issues
Traceback (most recent call last):
  File "D:\sectools\01漏洞分析\AppInfoScanner-master\app.py", line 100, in <module>
    main()
  File "D:\sectools\01漏洞分析\AppInfoScanner-master\app.py", line 96, in main
    cli()
  File "C:\Users\bqc\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bqc\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\bqc\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bqc\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bqc\AppData\Roaming\Python\Python311\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sectools\01漏洞分析\AppInfoScanner-master\app.py", line 44, in android
    raise e
  File "D:\sectools\01漏洞分析\AppInfoScanner-master\app.py", line 42, in android
    BaseTask("Android", inputs, rules, sniffer, threads, package).start()
  File "D:\sectools\01漏洞分析\AppInfoScanner-master\libs\task\base_task.py", line 47, in start
    task_info = self.__tast_control__()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sectools\01漏洞分析\AppInfoScanner-master\libs\task\base_task.py", line 89, in __tast_control__
    task_info = AndroidTask(cacar_path, self.package).start()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sectools\01漏洞分析\AppInfoScanner-master\libs\task\android_task.py", line 306, in start
    if self.__decode_file__(input_file_path) == "error":
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\sectools\01漏洞分析\AppInfoScanner-master\libs\task\android_task.py", line 386, in __decode_file__
    self.__decode_apk__(file_path, apktool_path, output_path)
  File "D:\sectools\01漏洞分析\AppInfoScanner-master\libs\task\android_task.py", line 424, in __decode_apk__
    raise Exception(file_path + ", Decompilation failed.")
<img width="1051" alt="07b67979ae9d6873e0bdb34335e31f6" src="https://github.com/kelvinBen/AppInfoScanner/assets/48121551/cc119602-f058-47db-93f0-b92afb110407">

**Comment by evaderPluto** [comment]
我遇上和你一样的问题，请问怎么解决呢？

**Comment by kelvinBen** [comment]
版本: 1.0.10版本已修复，使用过程中如还存在问题请再反馈
