### ISSUE TITLE
Could not decode arsc file. Decompilation failed.

### ISSUE THREAD

**Issue by ThanatosXingYu** [kelvinBen/AppInfoScanner#39]
C:\Users\admin\Desktop\Tools\AppInfoScanner>python app.py android -i release20230620jg.apk

[*] Create directory C:\Users\admin\Desktop\Tools\AppInfoScanner\out
[*] AI is analyzing filtering rules......
[*] The filtering rules obtained by AI are as follows: {'.*apache.org', '.*apple.com', '.*umeng.com', '.*localhost', '.*android.com', '.*github.com', '.*umengcloud.com', '.*w3school.com.cn', '.*.amap.com', '.*0.0.0.0', '.*w3.org', '.*slf4j.org', '.*127.0.0.1', '.*jpush.cn'}
java version "17.0.3" 2022-04-19 LTS
Java(TM) SE Runtime Environment (build 17.0.3+8-LTS-111)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.3+8-LTS-111, mixed mode, sharing)
15.2.2
We can't detect protect
I: Using Apktool 2.6.1 on release20230620jg.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:55)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:783)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
        at brut.androlib.Androlib.getResTable(Androlib.java:70)
        at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:247)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:79)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00750069
        at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:72)
        at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:70)
        at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:70)
        at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:50)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:78)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
        ... 8 more
[-] Decompilation failed, please submit error information at https://github.com/kelvinBen/AppInfoScanner/issues
Traceback (most recent call last):
  File "app.py", line 100, in <module>
    main()
  File "app.py", line 96, in main
    cli()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 44, in android
    raise e
  File "app.py", line 42, in android
    BaseTask("Android", inputs, rules, sniffer, threads, package).start()
  File "C:\Users\admin\Desktop\Tools\AppInfoScanner\libs\task\base_task.py", line 47, in start
    task_info = self.__tast_control__()
  File "C:\Users\admin\Desktop\Tools\AppInfoScanner\libs\task\base_task.py", line 89, in __tast_control__
    task_info = AndroidTask(cacar_path, self.package).start()
  File "C:\Users\admin\Desktop\Tools\AppInfoScanner\libs\task\android_task.py", line 306, in start
    if self.__decode_file__(input_file_path) == "error":
  File "C:\Users\admin\Desktop\Tools\AppInfoScanner\libs\task\android_task.py", line 386, in __decode_file__
    self.__decode_apk__(file_path, apktool_path, output_path)
  File "C:\Users\admin\Desktop\Tools\AppInfoScanner\libs\task\android_task.py", line 424, in __decode_apk__
    raise Exception(file_path + ", Decompilation failed.")
Exception: release20230620jg.apk, Decompilation failed.

**Comment by kelvinBen** [comment]
版本: 1.0.10版本已修复，使用过程中如还存在问题请再反馈
