### ISSUE TITLE
反编译失败

### ISSUE THREAD

**Issue by evaderPluto** [kelvinBen/AppInfoScanner#41]
报错信息如下：
```
[*] Create directory /root/桌面/AppInfoScanner/out
[*] Create directory /root/桌面/AppInfoScanner/download
[*] Create directory /root/桌面/AppInfoScanner/history
[*] AI is analyzing filtering rules......
[*] The filtering rules obtained by AI are as follows: {'.*jpush.cn', '.*umengcloud.com', '.*apple.com', '.*.amap.com', '.*apache.org', '.*w3.org', '.*0.0.0.0', '.*umeng.com', '.*android.com', '.*127.0.0.1', '.*github.com', '.*w3school.com.cn', '.*localhost'}
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Exception in thread "main" java.lang.UnsupportedClassVersionError: brut/apktool/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: brut.apktool.Main. Program will exit.
[-] Decompilation failed, please submit error information at https://github.com/kelvinBen/AppInfoScanner/issues
Traceback (most recent call last):
  File "/root/桌面/AppInfoScanner/app.py", line 72, in <module>
    main()
  File "/root/桌面/AppInfoScanner/app.py", line 69, in main
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/桌面/AppInfoScanner/app.py", line 32, in android
    raise e
  File "/root/桌面/AppInfoScanner/app.py", line 30, in android
    BaseTask("Android", inputs, rules, sniffer, threads, package).start()
  File "/root/桌面/AppInfoScanner/libs/task/base_task.py", line 46, in start
    task_info = self.__tast_control__()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/桌面/AppInfoScanner/libs/task/base_task.py", line 86, in __tast_control__
    task_info = AndroidTask(cacar_path,self.package).start()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/桌面/AppInfoScanner/libs/task/android_task.py", line 35, in start
    if self.__decode_file__(input_file_path) == "error":
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/桌面/AppInfoScanner/libs/task/android_task.py", line 50, in __decode_file__
    self.__decode_apk__(file_path,apktool_path,output_path)
  File "/root/桌面/AppInfoScanner/libs/task/android_task.py", line 86, in __decode_apk__
    raise Exception(file_path + ", Decompilation failed.")
Exception: /root/桌面/Illusion.apk, Decompilation failed.
```

**Comment by netuseradmin** [comment]
这个报错信息显示了一个程序创建目录的过程，并且展示了一些错误信息。具体来说：

- `Create directory /root/桌面/AppInfoScanner/out`：程序尝试创建一个名为`out`的目录，在路径`/root/桌面/AppInfoScanner/`下。
- `Create directory /root/桌面/AppInfoScanner/download`：程序尝试创建一个名为`download`的目录，在路径`/root/桌面/AppInfoScanner/`下。
- `Create directory /root/桌面/AppInfoScanner/history`：程序尝试创建一个名为`history`的目录，在路径`/root/桌面/AppInfoScanner/`下。

接下来的部分是分析过滤的规则
- `.*jpush.cn`：该规则匹配以`jpush.cn`结尾的所有字符串。
- `.*umengcloud.com`：该规则匹配以`umengcloud.com`结尾的所有字符串。
- `.*apple.com`：该规则匹配以`apple.com`结尾的所有字符串。
- `.*.amap.com`：该规则匹配包含`.amap.com`的所有字符串。
- `.*apache.org`：该规则匹配以`apache.org`结尾的所有字符串。
- `.*w3.org`：该规则匹配以`w3.org`结尾的所有字符串。
- `.*0.0.0.0`：该规则匹配以`0.0.0.0`结尾的所有字符串。
- `.*umeng.com`：该规则匹配以`umeng.com`结尾的所有字符串。
- `.*android.com`：该规则匹配以`android.com`结尾的所有字符串。
- `.*127.0.0.1`：该规则匹配以`127.0.0.1`结尾的所有字符串。
- `.*github.com`：该规则匹配以`github.com`结尾的所有字符串。
- `.*w3school.com.cn`：该规则匹配以`w3school.com.cn`结尾的所有字符串。
- `.*localhost`：该规则匹配以`localhost`结尾的所有字符串。

**Comment by kelvinBen** [comment]
版本: 1.0.10版本已修复，使用过程中如还存在问题请再反馈
