### ISSUE TITLE
用pip install frida-tools命令安装frida-tools报错

### ISSUE THREAD

**Issue by hejila** [kelvinBen/AppInfoScanner#47]
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting frida-tools
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ab/42/7823de1787e4c13c88c5de4caaf315365687d5425c9b484df2917bb6ca75/frida-tools-12.3.0.tar.gz (200 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "D:\soft\language\python_environment\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\soft\language\python_environment\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\soft\language\python_environment\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\hua'wei\AppData\Local\Temp\pip-build-env-ujw9tq2l\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\hua'wei\AppData\Local\Temp\pip-build-env-ujw9tq2l\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\hua'wei\AppData\Local\Temp\pip-build-env-ujw9tq2l\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\hua'wei\AppData\Local\Temp\pip-build-env-ujw9tq2l\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
        File "C:\Users\hua'wei\AppData\Local\Temp\pip-build-env-ujw9tq2l\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          _install_setup_requires(attrs)
        File "C:\Users\hua'wei\AppData\Local\Temp\pip-build-env-ujw9tq2l\overlay\Lib\site-packages\setuptools\__init__.py", line 71, in _install_setup_requires
          dist = MinimalDistribution(attrs)
        File "C:\Users\hua'wei\AppData\Local\Temp\pip-build-env-ujw9tq2l\overlay\Lib\site-packages\setuptools\__init__.py", line 53, in __init__
          super().__init__(filtered)
        File "C:\Users\hua'wei\AppData\Local\Temp\pip-build-env-ujw9tq2l\overlay\Lib\site-packages\setuptools\dist.py", line 301, in __init__
          for ep in metadata.entry_points(group='distutils.setup_keywords'):
      TypeError: entry_points() got an unexpected keyword argument 'group'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by hejila** [comment]
如何解决这个bug

**Comment by kelvinBen** [comment]
python -m pip install frida frida-tools 

版本: 1.0.10版本已修复，使用过程中如还存在问题请再反馈
